
--Creación de las tablas en el esquema public
CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(10) PRIMARY KEY,
    First_Name VARCHAR(20) NOT NULL,
    Middle_Name VARCHAR(20),
    First_Last_Name VARCHAR(20) NOT NULL,
    Second_Last_Name VARCHAR(20),
    Phone VARCHAR(15) NOT NULL,
    Date_of_birth DATE NOT NULL
);


CREATE TABLE SERVICE (
    SERVICE_ID VARCHAR(5) PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
    Description VARCHAR(50),
    Cost NUMERIC(10,2) NOT NULL
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID VARCHAR(5) PRIMARY KEY,
    First_Name VARCHAR(15) NOT NULL,
    Middle_Name VARCHAR(15),
    First_Last_Name VARCHAR(15) NOT NULL,
    Second_Last_Name VARCHAR(15),
    Phone VARCHAR(15) NOT NULL,
    Hiring_Date DATE NOT NULL,
    Salary NUMERIC(10,2) NOT NULL,
    State VARCHAR(9) NOT NULL,
    Certification VARCHAR(30) NOT NULL,
    Specialty VARCHAR(30) NOT NULL,
    User_name VARCHAR(30) NOT NULL,
    Password VARCHAR(15) NOT NULL
);

CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID VARCHAR(5) PRIMARY KEY,
    Date DATE NOT NULL,
    Hour TIME NOT NULL,
    State VARCHAR(20) NOT NULL,
    CUSTOMER_ID VARCHAR(10) NOT NULL,
    SERVICE_ID VARCHAR(5) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) 
    REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (SERVICE_ID) 
    REFERENCES SERVICE(SERVICE_ID)

);

CREATE TABLE APPOINTMENT_DETAILS (
    APPOINTMENT_DETAILS_ID VARCHAR(2) PRIMARY KEY,
    Cost NUMERIC(10,2) NOT NULL,
    EMPLOYEE_ID VARCHAR(5) NOT NULL,
    SERVICE_ID VARCHAR(5) NOT NULL,
    APPOINTMENT_ID VARCHAR(5) NOT NULL,
    FOREIGN KEY (EMPLOYEE_ID) 
    REFERENCES EMPLOYEE(EMPLOYEE_ID),
    FOREIGN KEY (SERVICE_ID) 
    REFERENCES SERVICE(SERVICE_ID),
    FOREIGN KEY (APPOINTMENT_ID) 
    REFERENCES APPOINTMENT(APPOINTMENT_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID VARCHAR(10) PRIMARY KEY,
    Payment_Method VARCHAR(15) NOT NULL,
    Payment_Date DATE NOT NULL,
    Payment_Amount NUMERIC(10,2) NOT NULL,
    APPOINTMENT_ID VARCHAR(5) NOT NULL,
    FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID)
);

CREATE TABLE MEDICAL_RECORD (
    MEDICAL_RECORD_ID VARCHAR(3) PRIMARY KEY,
    Date DATE NOT NULL,
    Description VARCHAR(200) NOT NULL,
    CUSTOMER_ID VARCHAR(10) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

